var instructions = [
"This is a game about deciphering a message, picked up",
"from deep space, as a series of numbers. ",
"",
"These numbers represent an image, if you can find it.",
"",
"The message is noisy, but contains a digital signature.",
"To find it, you'll need to do three things:",
"   1) set the thresehold for a 1 by dragging the gray box",
"    up and down",
"   2) set the number of seconds per sample ",
"   (in the input field below)",
"That will give you a series of 1s and 0s, but you're not ",
"done yet- you'll also need to guess at the pixels per row",
"in the transmitted image, so..  ",
"   3) set the pixels per row (in the input field below)",
"The top left shows the original signal, the bottom-",
"left the digital version, and the final image is rendered",
"on the right.",
"",
"Click to start"
];