var TYPE_DIRT   = 0;
var TYPE_WATER  = 1;
var TYPE_ROCK   = 2;
var TYPE_GAS    = 3;


var TYPE_COUNT  = 4;

var TYPE_COLORS = new Array();
TYPE_COLORS[TYPE_DIRT] = 'rgb(166,119,18)';
TYPE_COLORS[TYPE_WATER] = 'rgb(0,0,255)';
TYPE_COLORS[TYPE_ROCK] = 'rgb(124,122,118)';
TYPE_COLORS[TYPE_GAS] = 'rgb(204,232,241)';

TYPE_NAMES = new Array();
TYPE_NAMES[TYPE_DIRT] = 'Dirt';
TYPE_NAMES[TYPE_WATER] = 'Water';
TYPE_NAMES[TYPE_ROCK] = 'Rock';
TYPE_NAMES[TYPE_GAS] = 'Oxygen';