let itemData = {
    images: [
        {
            src: 'img/sprites.png',
            size: 100,
            id: 1
        },
    ],
    items: [
        {
            src: 1,
            x: 1,
            y: 0,
            name: 'mouse_squeak',
            inv: false,
            lvl: true,
            id: 1,
        },
        {
            src: 1,
            x: 2,
            y: 0,
            name: 'mouse_hat',
            inv: false,
            lvl: true,
            id: 2,
        },
        {
            src: 1,
            x: 0,
            y: 1,
            name: 'towel',
            inv: true,
            lvl: false,
            id: 3,
        },
        {
            src: 1,
            x: 1,
            y: 1,
            name: 'knife',
            inv: true,
            lvl: false,
            id: 4,
        },
        {
            src: 1,
            x: 2,
            y: 1,
            name: 'tomato',
            inv: false,
            lvl: true,
            id: 5,
        },
        {
            src: 1,
            x: 3,
            y: 1,
            name: 'corn',
            inv: false,
            lvl: true,
            id: 6,
        },
        {
            src: 1,
            x: 4,
            y: 1,
            name: 'ham',
            inv: false,
            lvl: true,
            id: 7,
        },
        {
            src: 1,
            x: 5,
            y: 1,
            name: 'beans',
            inv: false,
            lvl: true,
            id: 8,
        },
        {
            src: 1,
            x: 6,
            y: 1,
            name: 'garlic',
            inv: false,
            lvl: true,
            id: 9,
        },
        {
            src: 1,
            x: 7,
            y: 1,
            name: 'secret_jar',
            inv: false,
            lvl: true,
            id: 10,
        },
        {
            src: 1,
            x: 7,
            y: 2,
            name: 'jar_empty',
            inv: false,
            lvl: true,            
            id: 11,
        },
        {
            src: 1,
            x: 2,
            y: 2,
            name: 'crate',
            inv: false,
            lvl: true,
            id: 12,
        },
        {
            src: 1,
            x: 3,
            y: 2,
            name: 'mop',
            inv: false,
            lvl: true,
            id: 13,
        },
        {
            src: 1,
            x: 4,
            y: 2,
            name: 'pot_sauce',
            inv: false,
            lvl: true,
            id: 14,
        },
        {
            src: 1,
            x: 5,
            y: 2,
            name: 'coat rack',
            inv: false,
            lvl: true,
            id: 15,
        },
        {
            src: 1,
            x: 6,
            y: 2,
            name: 'bucket',
            inv: false,
            lvl: true,
            id: 16,
        },
        {
            src: 1,
            x: 2,
            y: 3,
            name: 'gourd',
            inv: false,
            lvl: true,
            id: 17,
        },
        {
            src: 1,
            x: 3,
            y: 3,
            name: 'mayo',
            inv: false,
            lvl: true,
            id: 23,
        },
        {
            src: 1,
            x: 4,
            y: 3,
            name: 'pot_water',
            inv: false,
            lvl: true,
            id: 18,
        },
        {
            src: 1,
            x: 5,
            y: 3,
            name: 'chopped tomato',
            inv: true,
            lvl: false,
            id: 19,
        },
        {
            src: 1,
            x: 6,
            y: 3,
            name: 'chopped garlic',
            inv: true,
            lvl: false,
            id: 20,
        },
        {
            src: 1,
            x: 7,
            y: 0,
            name: 'mouse eyes',
            inv: false,
            lvl: true,
            id: 21,
        },
        {
            src: 1,
            x: 0,
            y: 0,
            name: 'player',
            inv: false,
            lvl: true,
            id: 22,
        },
        {
            src: 1,
            x: 7,
            y: 3,
            name: 'onion',
            inv: false,
            lvl: true,
            id: 24,
        },        
        {
            src: 1,
            x: 3,
            y: 0,
            name: 'person1',
            inv: false,
            lvl: true,
            id: 25,
        },
        {
            src: 1,
            x: 4,
            y: 0,
            name: 'person2',
            inv: false,
            lvl: true,
            id: 26,
        },
        {
            src: 1,
            x: 5,
            y: 0,
            name: 'person3',
            inv: false,
            lvl: true,
            id: 27,
        },
        {
            src: 1,
            x: 6,
            y: 0,
            name: 'person5',
            inv: false,
            lvl: true,
            id: 28,
        },
    ]
};
