let stepTemplates = [
    'gave @[item] to @[living]',
    'used @[item] on @[level]',
    'defeated @[living]',
    'talked to @[living]',
    'danced with @[living]',
    'sold @[item] to @[living]',
    'helped @[living] with @[item]',
    'brandished @[item] at @[living]',
    'inspected @[level]'
];

let extraStatements = [
    'Footsteps echoed in the distance.',
    'Time was growing short.',
    'It reminded them of their youth.',
    'They paused to gather their thoughts.',
    'They were undaunted.'
]

let extraActions = [
];

let itemData = {
    images: [
        {
            src: 'img/StoryTimeItemSprites.png',
            size: 40,
            id: 1
        },
    ],
    items: [
        {
            src: 1,
            x: 1,
            y: 0,
            name: 'golden key',
            inv: true,
            lvl: true,
            id: 1,
        },
        {
            src: 1,
            x: 2,
            y: 0,
            name: 'silver key',
            inv: true,
            lvl: true,
            id: 2,
        },
        {
            src: 1,
            x: 3,
            y: 0,
            name: 'golden chest',
            inv: false,
            lvl: true,
            id: 3,
        },
        {
            src: 1,
            x: 4,
            y: 0,
            name: 'silver chest',
            inv: false,
            lvl: true,
            id: 4,
        },
        {
            src: 1,
            x: 0,
            y: 1,
            name: 'bread',
            inv: true,
            lvl: true,
            id: 5,
        },
        {
            src: 1,
            x: 1,
            y: 1,
            name: 'ham',
            inv: true,
            lvl: true,
            id: 6,
        },
        {
            src: 1,
            x: 2,
            y: 1,
            name: 'grapes',
            inv: true,
            lvl: true,
            id: 7,
        },
        {
            src: 1,
            x: 3,
            y: 1,
            name: 'apple',
            inv: true,
            lvl: true,
            id: 8,
        },
        {
            src: 1,
            x: 4,
            y: 1,
            name: 'cheese',
            inv: true,
            lvl: true,
            id: 9,
        },
        {
            src: 1,
            x: 5,
            y: 1,
            name: 'mushroom',
            inv: true,
            lvl: true,
            id: 10,
        },
        {
            src: 1,
            x: 0,
            y: 2,
            name: 'knife',
            inv: true,
            lvl: true,
            id: 11,
        },
        {
            src: 1,
            x: 1,
            y: 2,
            name: 'silver bar',
            inv: true,
            lvl: true,
            id: 12,
        },
        {
            src: 1,
            x: 2,
            y: 2,
            name: 'sword',
            inv: true,
            lvl: true,
            id: 13,
        },
        {
            src: 1,
            x: 1,
            y: 3,
            name: 'diamond ring',
            inv: true,
            lvl: true,
            id: 14,
        },
        {
            src: 1,
            x: 2,
            y: 3,
            name: 'gold ring',
            inv: true,
            lvl: true,
            id: 15,
        },
        {
            src: 1,
            x: 0,
            y: 5,
            name: 'serpent',
            inv: false,
            lvl: true,
            living: true,
            id: 16,
        },
        {
            src: 1,
            x: 1,
            y: 5,
            name: 'demon dog',
            inv: false,
            lvl: true,
            living: true,
            id: 17,
        },
        {
            src: 1,
            x: 2,
            y: 5,
            name: 'bat',
            inv: false,
            lvl: true,
            living: true,
            id: 18,
        },
        {
            src: 1,
            x: 3,
            y: 5,
            name: 'green frog',
            inv: false,
            lvl: true,
            living: true,
            id: 19,
        },
        {
            src: 1,
            x: 4,
            y: 5,
            name: 'orange frog',
            inv: false,
            lvl: true,
            living: true,
            id: 20,
        },        
        {
            src: 1,
            x: 5,
            y: 5,
            name: 'sorceror',
            inv: false,
            lvl: true,
            living: true,
            id: 21,
        },          
        {
            src: 1,
            x: 3,
            y: 3,
            name: 'empty bottle',
            inv: false,
            lvl: true,
            id: 23,
        }, 
        {
            src: 1,
            x: 4,
            y: 3,
            name: 'blue potion',
            inv: true,
            lvl: false,
            id: 24,
        },
        {
            src: 1,
            x: 5,
            y: 3,
            name: 'red potion',
            inv: false,
            lvl: true,
            id: 25,
        },        
        {
            src: 1,
            x: 6,
            y: 3,
            name: 'green potion',
            inv: false,
            lvl: true,
            id: 26,
        },        

    ]
};
